### ISSUE TITLE
doesn't work if game_path is executable shell script

### ISSUE THREAD

**Issue by ignatenkobrain** [sriemer/ugtrain#10]
```
$ ugtrain -P -S 0ad64.conf 
Loading config file "0ad64.conf".
Error while parsing config (line 2)!
game_path /usr/bin/0ad<--
```

```
$ file /usr/bin/0ad
/usr/bin/0ad: POSIX shell script, ASCII text executable
```

**Comment by ignatenkobrain** [comment]
if I will write `game_path 0ad` all works as expected

**Comment by sriemer** [comment]
Please provide the full 0ad64.conf. `game_path` requires `game_call` to be set to the same script name. Please see the sauerbraten example config for an example of a shell script calling the game.

**Comment by ignatenkobrain** [comment]
ah, yes. I should use game_call. Thanks!
